# Generated by Django 4.1.6 on 2023-02-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleScope',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]